name: "Roam Research backup"

on:
  push:
    branches:
      - main
  schedule:
      # Here you can change how often your backup runs. See https://crontab.guru/examples.html
      - cron: "0 * * * *"

jobs:
  backup:
    runs-on: ubuntu-latest
    name: Backup
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v2
        with:
          repository: ${{ secrets.BACKUP_REPO }}
          token: ${{ secrets.ACCESS_TOKEN }}
      
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      
